/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-07-25 12:34:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navigation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BuyingLiving%20v3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1469012652308L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n<script>\r\n\r\n\r\n$(function(){\r\n\t$('#msgNew').hide();\r\n\t\r\n\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'.length > 0){\r\n\t\tsetInterval(function(){newMSGcheck();},2000);\r\n\t\t}\r\n\t\r\n\tif(screen.width >700){\r\n\tvar sidebar = '<div id=\"msgNew\" style=\"display:none; background: url(resources/img/new.png); width:35px; height:35px; position:absolute; left: 50% ; top:200%\" ></div>'\r\n\tsidebar += '<ul><li><a href=\"myPage\" class=\"quick1\"><img src=\"resources/img/gbn-sidebar-1.png\" width=\"80px\" height=\"80px\" \ttitle=\"마이페이지\" alt=\"마이페이지\" /></a></li>'\r\n\tsidebar += '<li><a href=\"cartView\" class=\"quick2\"><img src=\"resources/img/gbn-sidebar-2.png\" width=\"80px\" height=\"80px\" title=\"장바구니\" alt=\"장바구니\" /></a></li>'\r\n\tsidebar += '<li><a href=\"qnaBoardView?currentPage=1\" class=\"quick3\"><img src=\"resources/img/gbn-sidebar-3.png\" width=\"80px\" height=\"70px\" title=\"QnA\" alt=\"QnA\" /></a></li>'\r\n\tsidebar += '<li><a href=\"freeBoardView?currentPage=1\" class=\"quick4\"><img src=\"resources/img/gbn-sidebar-4.png\" width=\"80px\" height=\"80px\" title=\"자유게시판\" alt=\"자유게시판\" /></a></li>'\r\n\tsidebar += '<li><a id=\"msgBox\" class=\"quick5\" sendId=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"resources/img/gbn-sidebar-5.png\" width=\"80px\" height=\"80px\" title=\"쪽지\" alt=\"쪽지\" /></a></li></ul>'\r\n\t\r\n\t$(\".gnbSidebar\").html(sidebar);\r\n\t\r\n\t}\r\n\r\n\t\r\n});\r\n\r\nfunction newMSGcheck(){\r\n\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'.length > 0){\r\n\r\n\t$.ajax({\r\n\t\tmethod : \"get\",\r\n\t\turl : \"newMSGcheck\",\r\n\t\tdata : \"loginId=\"+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n\t\tdataType : 'text',\r\n\t\tsuccess : function(response){\r\n\t\t\tif(response ===\"success\"){\r\n\t\t\t\t$('#msgNew').show();\r\n\t\t\t}else if(response===\"fail\"){\r\n\t\t\t\t$('#msgNew').hide();\r\n\t\t\t}\r\n\t\t\t\t\r\n\t\t}\r\n\t});\r\n\t}\r\n}\r\n\r\nfunction callMsgbox(text){\r\n\tvar url = \"selectOneMsgBox?sendId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&receiveId=\"+text;\r\n\t\r\n\twindow.open(url,'pop','resizable=yes scrollbars=yes');\r\n}\r\n</script>\r\n<!-- 사이드바 -->\r\n<style type=\"text/css\">\r\ndiv.gnbSidebar {\r\n\tposition: fixed;\r\n\ttop: 111px;\r\n\tright: 60px;\r\n\twidth: 51px;\r\n\theight: 150px;\r\n\tz-index: 10000;\r\n} /*height:225px*/\r\ndiv.gnbSidebar ul {\r\n\tdisplay: block;\r\n}\r\n\r\ndiv.gnbSidebar li {\r\n\tdisplay: list-item;\r\n\tlist-style: none;\r\n\tmargin: 0px;\r\n}\r\n</style>\r\n<!-- 사이드바 -->\r\n<div class=\"gnbSidebar\">\r\n\r\n</div>\r\n\t<!-- 사이드바 -->\r\n\r\n\r\n\r\n<div class=\"navigation\">\r\n\t\t\t<div class=\"secondary-navigation\">\r\n\t\t\t\t<div class=\"container\">\r\n\t\t\t\t\t<div class=\"contact\">\r\n\t\t\t\t\t \t\r\n\t\t\t\t\t \t<figure><strong>㏇ GO5조</strong></figure>\r\n\t\t\t\t\t\t<figure><strong>Phone:</strong>2016-07-06</figure>\r\n\t\t\t\t\t\t<figure><strong>Email:</strong><a href=\"mailto:go5조@SES.com\">go5조@SES.com</a></figure>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"user-area\">\r\n\t\t\t\t\t\t<div class=\"actions\">\r\n\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t\t\r\n\t\t\t<div class=\"container\">\r\n\t\t\t\t<header class=\"navbar\" id=\"top\" role=\"banner\">\r\n\t\t\t\t\t<div class=\"navbar-header\">\r\n\t\t\t\t\t\t<button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\"\r\n\t\t\t\t\t\t\tdata-target=\".bs-navbar-collapse\">\r\n\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n\t\t\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t<a class=\"navbar-brand nav logo\" href=\"index\"\r\n\t\t\t\t\t\t\ttitle=\"Real Estate WordPress Theme\" rel=\"home\"><img\r\n\t\t\t\t\t\t\tstyle=\"width: 240px; height: 22px;\" width=\"240px\" height=\"22px\"\r\n\t\t\t\t\t\t\tsrc=\"resources/img/logo.png\" alt=\"Real Estate WordPress Theme\" /></a><a\r\n\t\t\t\t\t\t\tclass=\"navbar-brand nav logo retina\"\r\n\t\t\t\t\t\t\thref=\"index\"\r\n\t\t\t\t\t\t\ttitle=\"Real Estate WordPress Theme\" rel=\"home\"><img\r\n\t\t\t\t\t\t\tstyle=\"width: 240px; height: 22px;\" width=\"240px\" height=\"22px\"\r\n\t\t\t\t\t\t\tsrc=\"resources/img/logo.png\" alt=\"Real Estate WordPress Theme\" /></a>\r\n\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<nav\r\n\t\t\t\t\t\tclass=\"collapse navbar-collapse bs-navbar-collapse navbar-right\">\r\n\t\t\t\t\t\t<ul id=\"menu-main-menu-header\" class=\"nav navbar-nav\">\r\n\t\t\t\t\t\t\t<li id=\"menu-item-54\"\r\n\t\t\t\t\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-48 current_page_item current-menu-ancestor current_page_ancestor menu-item-has-children has-child\"><a\r\n\t\t\t\t\t\t\t\thref=\"myPage\">마이페이지</a></li>\r\n\t\t\t\t\t\t\t<li id=\"menu-item-400\"\r\n\t\t\t\t\t\t\t\tclass=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children has-child\"><a\r\n\t\t\t\t\t\t\t\thref=\"cartView\">장바구니</a></li>\r\n\t\t\t\t\t\t\t<li id=\"menu-item-401\"\r\n\t\t\t\t\t\t\t\tclass=\"menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children has-child\"><a\r\n\t\t\t\t\t\t\t\thref=\"freeBoardView?currentPage=1\">자유게시판</a></li>\r\n\t\t\t\t\t\t\t<li id=\"menu-item-2258\"\r\n\t\t\t\t\t\t\t\tclass=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children has-child\"><a\r\n\t\t\t\t\t\t\t\thref=\"msgBox\" id=\"msgbox\" sendId=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">쪽지함</a></li>\r\n\t\t\t\t\t</nav>\r\n\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t</header>\r\n\t\t\t\t<!-- /.navbar -->\r\n\t\t\t</div>\r\n\t\t\t<!-- /.container -->\r\n\t\t</div>\r\n\t\t<!-- /.navigation -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/navigation.jsp(94,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n\t\t\t\t\t\t\t\t<a class=\"promoted\" href=\"joinView\" class=\"register\"><strong>회원가입</strong></a>\r\n\t\t\t\t\t\t\t\t<a class=\"promoted\" href=\"brokerJoinView\" class=\"register\"\r\n\t\t\t\t\t\t\t\t\tstyle=\"color: orange;\"><strong>중개사가입</strong></a>\r\n\t\t\t\t\t\t\t\t<a href=\"loginView\" class=\"sing-in\">로그인</a>\r\n\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/navigation.jsp(100,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n\t\t\t\t\t\t\t\t<span> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("님 로그인 중 &nbsp; &nbsp;&nbsp;&nbsp;</span>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<a href=\"myPage\" class=\"sing-in\">My Page</a>\r\n\t\t\t\t\t\t\t\t<a href=\"logout\" class=\"sing-in\">로그아웃</a>\r\n\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
